[package]
name = "paho-mqtt3as-sys"
version = "0.2.0"
authors = ["Frank Pagliughi <fpagliughi@mindspring.com>"]
package = "build.rs"
description = """
Rust wrapper for the Paho MQTT C Client Library.
"""

[dependencies]

[build-dependencies]
bindgen = "0.30.0"

